
export const ActionTypes = {
    GET_NUMBER_CART: 'GET_NUMBER_CART',
    ADD_TO_CART: 'ADD_TO_CART',
    INCREMENT_QUANTITY: 'INCREMENT_QUANTITY',
    DECREASE_QUANTITY: 'DECREASE_QUANTITY',
    DELETE_CART: 'DELETE_CART',
    EMPTY_CART: 'EMPTY_CART',
    GET_TOTAL_CART: 'GET_TOTAL_CART',
    ADD_TO_FAVORITES: 'ADD_TO_FAVORITES',
    REMOVE_FROM_FAVORITES: 'REMOVE_FROM_FAVORITES'

}
